CREATE OR REPLACE TEMP TABLE AGGREGATE_APPAREL_BASE AS
SELECT DISTINCT EXTERNALORDERID,
                CUSTOMERORDERTYPE,
                COUNT(DISTINCT ORDERID) AS ORDERCOUNT
FROM
(SELECT 
cus.ORDDATE,
cus.ORDERDATE,
cus.EXTERNALORDERID, 
cus.CUSTOMERORDERTYPE,
cus.ORDERTOTAL,
cus.BILLSTATE,
st.ORDERID,
st.STR_ID,
st.SHIPMENTTYPE,
so.SKU,
so.ORIGINALQUANTITY
FROM KSFPA.OMS.CUSTOMERORDER_REALTIME cus
INNER JOIN KSFPA.OMS.STOREORDER_REALTIME st
ON (st.EXTERNALORDERID = cus.EXTERNALORDERID)
INNER JOIN KSFPA.OMS.STOREORDERITEMS_REALTIME so
ON (so.ORDERID = st.ORDERID)
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_PRODUCT PROD
ON so.SKU = PROD.PRODUCT_KEYCODE
WHERE TO_DATE(cus.ORDERDATE) BETWEEN '2022-06-27' AND '2024-05-12'
AND st.STR_ID NOT IN ('9998','9999','9996','9997')
AND PROD.RBU_CODE IN( '100','150','200'))
WHERE LTRIM(RTRIM(SHIPMENTTYPE)) = 'Original'

-- AND EXTERNALORDERID= 72435489
GROUP BY 1,2;



CREATE OR REPLACE TEMP TABLE AGGREGATED_AOV_ORDERS_APPAREL AS
SELECT ACCOUNTING_YEAR,
       ACCOUNTING_WEEK_NUMBER_IN_YEAR,
       FY_PW,
       CUSTOMERORDERTYPE,
       COUNT(DISTINCT(CASE WHEN ORDERCOUNT >1 THEN EXTERNALORDERID END)) AS AGGREGATED_ORDERS,
       SUM(CASE WHEN ORDERCOUNT >1 THEN SALES END)/COUNT(DISTINCT(CASE WHEN ORDERCOUNT >1 
       THEN EXTERNALORDERID END)) AS AGGREGATED_AOV,
       SUM(CASE WHEN ORDERCOUNT =1 THEN SALES END)/COUNT(DISTINCT(CASE WHEN ORDERCOUNT =1
       THEN EXTERNALORDERID END)) AS NON_AGGREGATED_AOV
FROM 
(SELECT DISTINCT ACCOUNTING_YEAR,
        ACCOUNTING_WEEK_NUMBER_IN_YEAR,
        FY_PW,
     EXTERNALORDERID,
     CUSTOMERORDERTYPE,
     SALES,
     ORDERCOUNT
     FROM
(SELECT DISTINCT ACCOUNTING_YEAR,
        ACCOUNTING_WEEK_NUMBER_IN_YEAR,
     CONCAT('FY',ACCOUNTING_YEAR,'P',RIGHT(ACCOUNTING_PERIOD_NUMBER,2),'W',ACCOUNTING_WEEK_NUMBER)                AS FY_PW,
     so.EXTERNALORDERID,
     cus.CUSTOMERORDERTYPE,
     soi.SKU,
     so.STOREORDERTOTAL AS SALES,
     AT.ORDERCOUNT
FROM KSFPA.OMS.CUSTOMERORDER_REALTIME cus 
INNER JOIN KSFPA.OMS.STOREORDER_REALTIME so
ON (so.EXTERNALORDERID = cus.EXTERNALORDERID)
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_DATE DD
ON DD.DATE = cus.orddate 
INNER JOIN KSFPA.OMS.STOREORDERITEMS_REALTIME soi
ON soi.ORDERID = so.ORDERID
INNER JOIN KSFPA.ONLINE_UGAM_PVT.AGGREGATE_APPAREL_BASE AT
ON AT.EXTERNALORDERID = cus.EXTERNALORDERID
INNER JOIN KSF_SOPHIA_DATA_INTELLIGENCE_HUB_PROD.COMMON_DIMENSIONS.DIM_PRODUCT PROD
ON soi.SKU = PROD.PRODUCT_KEYCODE
WHERE LTRIM(RTRIM(SHIPMENTTYPE)) = 'Original'
-- AND so.EXTERNALORDERID = 354984850
AND TO_DATE(cus.ORDERDATE) BETWEEN '2022-06-27' AND '2024-05-12'
AND so.STR_ID NOT IN ('9998','9999','9996','9997')
AND TO_VARCHAR(PRODUCT_KEYCODE) != 'undefined'
AND PROD.RBU_CODE  IN( '100','150','200') -- RBU Code for Apparel
--GROUP BY 1,2,3,4,5
ORDER BY 1,2)
GROUP BY 1,2,3,4,5,6,7)
GROUP BY 1,2,3,4;


//Aggregate Value
SELECT AG1.FY_PW,
        DENSE_RANK() OVER(ORDER BY AG1.FY_PW DESC) AS FY_PW_RANK,
        AG1.CUSTOMERORDERTYPE,
        (AG1.AGGREGATED_AOV - AG1.NON_AGGREGATED_AOV)*AG1.AGGREGATED_ORDERS AS 
        TY_AGGREGATED_VALUE,
        (AG2.AGGREGATED_AOV - AG2.NON_AGGREGATED_AOV)*AG2.AGGREGATED_ORDERS AS                        LY_AGGREGATED_VALUE,
FROM AGGREGATED_AOV_ORDERS_APPAREL AG1
INNER JOIN AGGREGATED_AOV_ORDERS_APPAREL AG2
ON AG1.ACCOUNTING_YEAR-1= AG2.ACCOUNTING_YEAR
AND AG1.ACCOUNTING_WEEK_NUMBER_IN_YEAR = AG2.ACCOUNTING_WEEK_NUMBER_IN_YEAR
AND AG1.CUSTOMERORDERTYPE = AG2.CUSTOMERORDERTYPE;